version: "3.7"

x-php-cli: &php-cli
    user: www-data
    volumes:
        - ./:/app
    depends_on:
        - redis
        - postgres

services:
    nginx:
        build: ./docker/local/nginx
        volumes:
            - ./:/app
            - ./storage/app/public:/app/public/storage
        ports:
            - "8080:80"
        depends_on:
            - php-fpm

    php-fpm:
        build: ./docker/local/php-fpm
        volumes:
            - ./:/app
        depends_on:
            - postgres

    schedule:
        build: ./docker/local/php-cli
        <<: *php-cli
        entrypoint: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"

    cli:
        build: ./docker/local/php-cli
        <<: *php-cli
        tty: yes
        entrypoint: bash

    redis:
        image: redis
        ports:
            - "6380:6379"

    postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "55432:5432"

    docs:
        image: redocly/redoc
        ports:
            - 8123:80
        environment:
            - PAGE_TITLE=UML
            - SPEC_URL=docs/api.yaml
        volumes:
            - ./docs:/usr/share/nginx/html/docs

volumes:
    db:
